name: build
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          # أضفنا libjpeg-dev و libpng-dev لضمان قراءة أيقونة اللعبة وصورها
          sudo apt install -y git zip unzip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev python3-dev libjpeg-dev libpng-dev
          pip install --upgrade pip
          pip install "cython<3.0.0" buildozer setuptools

      - name: Build with Buildozer
        run: |
          # هذا الأمر يوافق تلقائياً على رخص SDK ويقوم بالبناء
          yes | buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "yes"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartMindGame-Build
          path: bin/*.apk
